language: generic

matrix:
  include:
    - env: TARGET=i686-unknown-linux-gnu
      addons:
        apt:
          packages:
          - gcc-multilib
    - env: TARGET=x86_64-unknown-linux-gnu
    - env: TARGET=x86_64-unknown-linux-musl
      dist: trusty
      sudo: required
      addons:
        apt:
          packages:
          - musl-tools
          - libbz2-dev
    - env: TARGET=x86_64-pc-windows-gnu
      dist: trusty
      addons:
        apt:
          packages:
          - gcc-mingw-w64
          - gcc-mingw-w64-i686
          - gcc-mingw-w64-x86-64
          - binutils-mingw-w64-x86-64
          - binutils-mingw-w64-i686
          - libbz2-dev

install:
  - export PATH="$PATH:$HOME/.cargo/bin"
  - curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain=stable
  - rustc -V
  - cargo -V

script:
  - bash ci.sh

branches:
  only:
    - master
