language: generic

matrix:
  include:
    - os: linux
      env: TARGET=armv7-unknown-linux-gnueabihf
      addons:
        apt:
          packages: &armhf
          - gcc-arm-linux-gnueabihf
          - libc6-armhf-cross
          - libc6-dev-armhf-cross
    - os: linux
      env: TARGET=x86_64-unknown-linux-musl
      dist: trusty
      sudo: required
      addons:
        apt:
          packages:
          - musl-tools
          - libbz2-dev
    - os: linux
      env: TARGET=x86_64-pc-windows-gnu
      dist: trusty
      addons:
        apt:
          packages:
          - gcc-mingw-w64
          - gcc-mingw-w64-x86-64
          - binutils-mingw-w64-x86-64
          - libbz2-dev
    - os: osx
      env: TARGET=x86_64-apple-darwin

install:
  - export PATH="$PATH:$HOME/.cargo/bin"
  - curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain=stable
  - rustc -V
  - cargo -V

script:
  - bash ci.sh

deploy:
  provider: releases
  api_key:
    secure:
      OY6y0xRhlGSBH+3+7+7K6s4pp0Tf3BA61NAubEK4gpO23AKfyJUK+vqqCbdo06Z0E4QO4O1ke6fot7Gq9EdxJmsl/Kk5LDd9Rv3BXSYdjPupzs7coYuD8wv10NfAX6ETd9ITyPim2Zq6bq8nx1S2ESTpos/js1HCtVW3nrlCV58=
  skip_cleanup: true
  file:
    - "geckodriver-$TRAVIS_TAG.tar.gz"
    - "geckodriver-$TRAVIS_TAG-arm7hf.tar.gz"
    - "geckodriver-$TRAVIS_TAG-linux64.tar.gz"
    - "geckodriver-$TRAVIS_TAG-mac.tar.gz"
    - "geckodriver-$TRAVIS_TAG-win64.zip"
  on:
    tags: true
    repo: mozilla/geckodriver
