[package]
name = "wires"
version = "0.7.1"
authors = ["James Graham <james@hoppipolla.co.uk>"]
description = "Proxy for using WebDriver clients to interact with Gecko-based browsers."
repository = "https://github.com/jgraham/wires"
license = "MPL-2.0"

[dependencies]
argparse = "0.2.1"
env_logger = "0.3.2"
hyper = {version = "0.9", default-features = false}
lazy_static = "0.1"
log = "0.3"
mozprofile = "0.2"
mozrunner = "0.2"
regex = "0.1.47"
rustc-serialize = "0.3.16"
uuid = "0.1.18"
webdriver = "0.10"
zip = "0.1.16"