[package]
name = "geckodriver"
version = "0.14.0"
authors = [
  "James Graham <james@hoppipolla.co.uk>",
  "Andreas Tolfsen <ato@mozilla.com>",
]
description = "Proxy for using WebDriver clients to interact with Gecko-based browsers."
keywords = ["webdriver", "w3c", "httpd", "mozilla", "firefox"]
repository = "https://github.com/mozilla/geckodriver"
readme = "README.md"
license = "MPL-2.0"

[dependencies]
chrono = "=0.2.25"
clap = {version = "=2.20.3", default-features = false, features = ["suggestions", "wrap_help"]}
hyper = "0.10"
lazy_static = "0.1"
log = "0.3"
mozprofile = "0.2"
mozrunner = "0.3"
regex = "0.2"
rustc-serialize = "0.3"
slog = "1"
slog-atomic = "0.4"
slog-stdlog = "1"
slog-stream = "1"
webdriver = "0.22"
zip = "0.1"

# As a temporary workaround we pin certain dependencies exactly so that
# cargo will not complain about missing vendored crate versions when we
# build geckodriver from mozilla-central.
#
# We do not quite know yet why `./mach vendor rust` does not transitively
# vendor dependencies' dependencies, but the following list is the
# current available crate versions under third_party/rust that we can use.
gcc = "=0.3.42"
num = "=0.1.36"
num_cpus = "=1.2.1"
num-integer = "=0.1.32"
num-traits = "=0.1.36"
term_size = "=0.2.2"
thread_local = "=0.3.2"
