[package]
name = "wires"
version = "0.6.1"
authors = ["James Graham <james@hoppipolla.co.uk>"]
description = "Proxy for using WebDriver clients to interact with Gecko-based browsers."
repository = "https://github.com/jgraham/wires"
license = "MPL-2.0"

[dependencies]
env_logger = "0.3.2"
hyper = {version = "0.7.2", default-features = false}
log = "0.3.5"
mozprofile = "0.1.0"
mozrunner = "0.1.0"
rustc-serialize = "0.3.16"
uuid = "0.1.18"
webdriver = "0.6.0"
regex = "0.1.47"
argparse = "0.2.1"
