[package]

name = "wires"
version = "0.0.1"
authors = ["James Graham <james@hoppipolla.co.uk>"]
build = "make"

[dependencies]
getopts = "0.1.4"
log = "0.1.9"
rustc-serialize = "0.2.7"

[dependencies.hyper]
git = "https://github.com/hyperium/hyper.git"

[dependencies.uuid]
git = "https://github.com/rust-lang/uuid.git"

