[package]
name = "geckodriver"
version = "0.10.0"
authors = [
  "James Graham <james@hoppipolla.co.uk>",
  "Andreas Tolfsen <ato@mozilla.com>",
]
description = "Proxy for using WebDriver clients to interact with Gecko-based browsers."
keywords = ["webdriver", "w3c", "proxy", "httpd", "mozilla", "firefox"]
repository = "https://github.com/mozilla/geckodriver"
readme = "README.md"
license = "MPL-2.0"

[dependencies]
chrono = "^0.2"
hyper = {version = "0.9", default-features = false}
lazy_static = "0.1"
log = "0.3"
mozprofile = "0.2"
mozrunner = "^0.3.1"
regex = "0.1.47"
rustc-serialize = "0.3.16"
slog = "1"
slog-atomic = "0.4"
slog-stdlog = "1"
slog-stream = "1"
uuid = "0.1.18"
webdriver = "0.15.0"
zip = "0.1.16"

[dependencies.clap]
version = "2.9"
default-features = false
features = ["suggestions", "wrap_help"]
