[package]
name = "wires"
version = "0.0.1"
authors = ["James Graham <james@hoppipolla.co.uk>"]

[dependencies]
getopts = "=0.1.4"
log = "=0.1.9"
rustc-serialize = "=0.2.7"
uuid = "=0.1.7"

[dependencies.argparse]
git = "http://github.com/tailhook/rust-argparse.git"

[dependencies.webdriver]
path = "../webdriver"

[dependencies.mozprofile]
path = "../rust_mozprofile"

[dependencies.mozrunner]
path = "../rust_mozrunner"

[dependencies.hyper]
git = "https://github.com/servo/hyper"
branch = "old_servo_new_cookies"
