[package]
name = "wires"
version = "0.0.1"
authors = ["James Graham <james@hoppipolla.co.uk>"]

[dependencies]
getopts = "=0.1.4"
log = "=0.1.9"
rustc-serialize = "=0.2.7"
uuid = "=0.1.7"

[dependencies.argparse]
git = "http://github.com/tailhook/rust-argparse.git"

[dependencies.webdriver]
git = "http://github.com/jgraham/webdriver-rust.git"

[dependencies.mozprofile]
git = "http://github.com/jgraham/rust_mozprofile.git"

[dependencies.mozrunner]
git = "http://github.com/jgraham/rust_mozrunner.git"

[dependencies.hyper]
git = "https://github.com/servo/hyper"
branch = "old_servo_new_cookies"
